paths:
  raw_data: "../data/raw/"
  processed_data: "../data/processed/"
  features: "../data/features/"
  models: "../models/"
  results: "../results/"

dataset:
  cremad:
    path: "./data/raw/cremad/"
    sample_rate: 16000
    emotions:
      "ANG": "angry"
      "DIS": "disgust"
      "FEA": "fear"
      "HAP": "happy"
      "NEU": "neutral"
      "SAD": "sad"
    intensity:
      "LO": "low"
      "MD": "medium"
      "HI": "high"
      "XX": "unspecified"

preprocessing:
  normalize: true
  noise_reduction: true
  segment_length_ms: 3000
  hop_length_ms: 1000

features:
  mfcc:
    n_mfcc: 13
    include_delta: true
    include_delta_delta: true
  prosodic:
    extract_pitch: true
    extract_energy: true
    extract_zero_crossing_rate: true
  spectral:
    extract_spectral_centroid: true
    extract_spectral_rolloff: true
    extract_spectral_flux: true
    extract_spectral_bandwidth: true

model:
  random_state: 42
  test_size: 0.2
  validation_size: 0.2
  models_to_train:
    - "nn"
    - "svm"
    - "random_forest"
    - "xgboost"
  hyperparameter_tuning:
    perform: true
    cv_folds: 5
  feature_selection:
    method: "selectk"  # Options: "selectk", "rfe", "none"
    k_features: 100    # Number of features to select
  model_params:
    svm:
      C: [0.1, 1, 10, 100]
      gamma: ['scale', 'auto', 0.1, 0.01] 
      kernel: ['rbf', 'linear', 'poly']
    random_forest:
      n_estimators: [100, 200, 300]
      max_depth: [None, 10, 20, 30]
      min_samples_split: [2, 5, 10]
      min_samples_leaf: [1, 2, 4]
    xgboost:
      n_estimators: [100, 200, 300]
      max_depth: [3, 5, 7, 9]
      learning_rate: [0.01, 0.05, 0.1, 0.2]
      subsample: [0.8, 0.9, 1.0]
      colsample_bytree: [0.8, 0.9, 1.0]
  device: "cuda"  # Options: "cuda", "cpu"
  gpu:
    use_gpu: true
    precision: "float32"  # Options: "float32", "float16" (for mixed precision)
    batch_size: 64  # Adjust based on your GPU memory
    hidden_size: 128

evaluation:
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1"